# https://hub.docker.com/r/library/python/tags/
image: "python:3.7"

before_script:
- python3 --version
- pip3 install --upgrade pip setuptools

stages:
- build
- test
- deploy

variables:
  GIT_DEPTH: 1
  LC_ALL: "C"
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  HIVEMIND_DB_NAME: $HIVEMIND_DB_NAME
  HIVEMIND_SOURCE_HIVED_URL: $HIVEMIND_SOURCE_HIVED_URL

hivemind_build:
  stage: build
  script:
    - "python3 setup.py build"
    - ls -l dist/
#    - "python3 setup.py install --prefix $CI_PROJECT_DIR/hivemind-install"
  artifact:
    paths:
      - dist/
    expire_in: 1 week
  tags:
     - hivemind

hivemind_deploy:
  stage: deploy
  depends: build
  script:
    - ls -l dist/*
    - "echo Attempting to recreate database $HIVEMIND_DB_NAME"
    - "echo Attempting to starting hive sync using hived node: $HIVEMIND_SOURCE_HIVED_URL"
  tags:
     - hivemind
