version: '3'
services:
  init-db:
    build:
      context: ./postgres/docker
      dockerfile: Dockerfile
    image: hivemind:postgres
    container_name: hivemind-init-db
    command: bash -c "run_db.sh init"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
        - ./postgres/init:/docker-entrypoint-initdb.d 
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/docker/postgresql.conf:/etc/postgresql.conf
  postgres-db:
    build:
      context: ./postgres/docker
      dockerfile: Dockerfile
    image: hivemind:postgres
    container_name: $POSTGRES_NAME
    user: 1000:1000
    command: >
      bash -c "
        run_db.sh wait_for_finish hivemind-init-db
        run_db.sh run
      "
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/docker/postgresql.conf:/etc/postgresql.conf     
  hivemind-init-sync:
    depends_on:
      - postgres-db
    image: hivemind:latest
    container_name: hivemind-init-sync
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "run_hivemind.sh sync"
    environment:
      POSTGRES_IP: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      HIVE_SYNC_URL: $HIVE_SYNC_URL
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_NAME:$POSTGRES_PORT/$POSTGRES_DB
  hivemind-server:
    depends_on:
      - postgres-db
      - hivemind-init-sync
    image: hivemind:latest
    container_name: hivemind-server
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        run_hivemind.sh wait_for_finish hivemind-init-sync
        run_hivemind.sh sync_and_server
      "
    environment:
      POSTGRES_IP: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      HIVE_SYNC_URL: $HIVE_SYNC_URL
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_NAME:$POSTGRES_PORT/$POSTGRES_DB
    ports:
        - 8080:8080
volumes:
  postgres-db:
    driver: local