version: '3'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: unless-stopped
    volumes:
        - postgres-db:/var/lib/postgresql/data
  hivemind:
    depends_on:
      - postgres-db
    image: hivemind:latest
    build: .
    command: >
       hive sync --test-max-block=5000000 --test-profile=False --exit-after-sync --steemd-url '{"default" : $HIVE_SYNC_URL}' --database-url $DATABASE_URL
       tail -f /dev/null
    environment:
      DATABASE_URL: $DATABASE_URL
    restart: unless-stopped
volumes:
  postgres-db:
    driver: local