version: '3'
services:
  hivemind:
    image: hivemind:postgres
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@hivemind:$POSTGRES_PORT/$POSTGRES_DB
      HIVE_SYNC_URL: $HIVE_SYNC_URL
    restart: unless-stopped
    volumes:
        - hivemind:/var/lib/postgresql/data
volumes:
  hivemind:
    driver: local